### PR TITLE
Httpoxy

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by tokuhirom** [comment]
review plz

**Comment by kazuho** [comment]
```
+    if (defined $ENV{REQUEST_METHOD}) {
+        $self->{proxy} = $ENV{CGI_HTTP_PROXY} || '';
+    } else {
+        $self->{proxy} = $ENV{HTTP_PROXY} || '';
+    }
```

It seems like we should set either of `CGI_HTTP_PROXY` or `HTTP_PROXY` depending on how the code is used.

That doesn't seem like a good idea to me. Wouldn't it be better to have a single environment variable that could cover all the cases?

**Comment by mattn** [comment]
Okay, we expect same behavior to LWP.

|No|REQUEST_METHOD|HTTP_PROXY|CGI_HTTP_PROXY|Set proxy     |
|--:|:------------:|:--------:|:------------:|:------------:|
| 1|-             |-         |-             |              |
| 2|O             |-         |-             |              |
| 3|-             |O         |-             |HTTP_PROXY    |
| 4|O             |O         |-             |              |
| 5|-             |-         |O             |CGI_HTTP_PROXY|
| 6|O             |-         |O             |              |
| 7|-             |O         |O             |CGI_HTTP_PROXY|
| 8|O             |O         |O             |              |

Will update in later.

**Comment by kazuho** [comment]
```
    if (!defined $ENV{REQUEST_METHOD}) {
        $self->{proxy} = $ENV{HTTP_PROXY} || '';
    }
    if (!defined $ENV{HTTP_PROXY} && defined $ENV{CGI_HTTP_PROXY}) {
        $self->{proxy} = $ENV{CGI_HTTP_PROXY} || '';
    }
```
With this code, `CGI_HTTP_PROXY` would not be used if both `REQUEST_METHOD` and `HTTP_PROXY` are set. Is that the intended behavior?

**Comment by miyagawa** [comment]
I prefer HTTP::Tiny's solution:
https://metacpan.org/source/DAGOLDEN/HTTP-Tiny-0.058/lib/HTTP/Tiny.pm#L154

This allows using `http_proxy` (lower-case) in both CGI and non-CGI environment, while rejecting the upper-case `HTTP_PROXY` in CGI environment.

**Comment by mattn** [comment]
Do you prefer using CGI_HTTP_PROXY/cgi_http_proxy both also?

**Comment by mattn** [comment]
Finally, I removed CGI_HTTP_PROXY as @miyagawa said in above. If you prefer CGI_HTTP_PROXY although, please do following.

```
curl -s https://gist.githubusercontent.com/mattn/2884397dd0ca977577cd1d0f7d9f32cc/raw/df94a3e4fa0afa0f87d1b39c226d0232f4ab69d7/0001-Add-CGI_HTTP_PROXY.patch | git am
```

If you don't, please merge this pull-request.

**Comment by miyagawa** [comment]
LGTM

**Pull request merged**
