### PR TITLE
Status 100

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
status message Continue should be replaced for 101.

**Comment by syohex** [comment]
Looks good.

**Comment by mattn** [comment]
Do you like squashed commits?

**Comment by syohex** [comment]
As you like. I suppose there are no wrong commits, so it is not necessary to squash commits.

**Comment by syohex** [comment]
@mattn Are you going to squash commits ? If you are not, then I merge this PR.

**Comment by mattn** [comment]
No. I'm just picking my nose.

**Comment by syohex** [comment]
Thanks

**Comment by mattn** [comment]
:metal:

**Pull request merged**
